{
  "version": 1,
  "analyzers": [
      {
          "name": "python",
          "enabled": true,
          "runtime_version": "3.x.x"
      }
  ],
  "test_patterns": [
      "tests/",
      "api/test_*.py"
  ],
  "exclude_patterns": [
      "setup.py",
      "a.py"
  ]
}
